### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by the94air** [pascalbaljetmedia/laravel-single-session#2]
> This package prevents a User from being logged in more than once. It destroys the previous session when a User logs in and thereby allowing only one session per user. 

Does this mean I can leave the login page without `guest:web` middleware?

**Comment by pascalbaljet** [comment]
The guest middleware just checks if a user is logged in. This package checks if a user is not logged in twice, for example in two different browsers.

**Comment by the94air** [comment]
That is so cool. I think I am gonna dive deep into the source code. Thanks.
