### ISSUE TITLE
Custom logout message. 

### ISSUE THREAD

**Issue by ronlinet** [pascalbaljetmedia/laravel-single-session#5]
Would you consider to include a custom logout message ? 
Something like 'Multiple session detected for use@email.com please login again'.  
Thank you for your time.

**Comment by pascalbaljet** [comment]
Whenever a session gets destroyed, the `UserSessionWasDestroyed` event will be dispatched. You could bind a listener to it and handle your messaging from there.

**Comment by ronlinet** [comment]
UserSessionWasDestroyed is a generic event which may be generated by this package but also by many other reasons. So to attached a 'Multiple session' warning to all destroyed sessions may be confusing.
